version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
    assignees:
      - "john0isaac"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      node-requirements:
        patterns:
          - "*"
    assignees:
      - "john0isaac"

  # Maintain dependencies for uv
  - package-ecosystem: "uv"
    directory: "/src"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      python-requirements:
        patterns:
          - "*"
    assignees:
      - "john0isaac"
