name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: cd ./frontend && npm install --include=dev
      - name: Run prettier on frontend
        run: cd ./frontend && npm run check-format
      - name: Run eslint on frontend
        run: cd ./frontend && npm run lint
