name: Python Linter and Formatter

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'

  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

  workflow_dispatch:

permissions:
  contents: read

jobs:
    check-format-lint:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
          with:
                python-version: 3.12
        - uses: astral-sh/setup-uv@v8.0.0
          with:
                enable-cache: true
        - name: Install dependencies
          run: |
            uv tool install ruff
        - name: Check linting with ruff
          run: |
            uv tool run ruff check .
        - name: Check formatting with ruff
          run: |
            uv tool run ruff format --check .
