name: Python Static Analysis

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'

  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

  workflow_dispatch:

permissions:
  contents: read

jobs:
    check-static-analysis:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: actions/setup-python@v6
          with:
                python-version: 3.12
        - uses: astral-sh/setup-uv@v5
          with:
                enable-cache: true
        - name: Install dependencies
          run: |
            uv sync --directory src --group lint
        - name: Check mypy
          run: |
            uv run --project src mypy .
