name: Python Unit tests

on:
  push:
    branches: [ main ]
    paths:
      - "**.py"
      - "frontend/**"
      - "src/uv.lock"
      - "src/pyproject.toml"

  pull_request:
    branches: [ main ]
    paths:
      - "**.py"
      - "frontend/**"
      - "src/uv.lock"
      - "src/pyproject.toml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test_package:

    name: Test ${{ matrix.os }} Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python_version: ["3.10", "3.11", "3.12"]
    steps:
        - uses: actions/checkout@v6
        - name: Setup python
          uses: actions/setup-python@v6
          with:
            python-version: ${{ matrix.python_version }}
            architecture: x64
        - uses: astral-sh/setup-uv@v5
          with:
            enable-cache: true
        - name: Setup node
          uses: actions/setup-node@v6
          with:
            node-version: 22
        - name: Build frontend
          run: |
            cd ./frontend
            npm install
            npm run build
        - name: Install dependencies
          run: |
            uv sync --directory src
        - name: Run tests
          run: uv run --directory src pytest
